# Generated by Django 5.2 on 2025-04-03 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blended_at', models.DateTimeField(default=None, null=True)),
                ('gross_weight', models.FloatField(default=None, null=True)),
                ('tare_weight', models.FloatField(default=None, null=True)),
                ('total_tons', models.FloatField(default=None, null=True)),
                ('blend_status', models.CharField(blank=True, max_length=2)),
                ('bag_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.bag')),
            ],
        ),
    ]
